services:
  weather-mcp:
    build: ./weather-mcp
    container_name: weather-mcp
    ports:
      - "8000:8000"
    stdin_open: true
    tty: true
    command: ["uv", "run", "main_http.py"]

  ui-weather:
    build: ./ui-weather
    container_name: ui-weather
    ports:
      - "4200:4200"
    stdin_open: true
    tty: true
    depends_on:
      - weather-mcp
